export class WebAudioBackend {
  constructor(AudioContextClass = globalThis.AudioContext ?? globalThis.webkitAudioContext) { this.AudioContextClass = AudioContextClass; this.context = null; this.buses = new Map(); }
  async init() { if (!this.AudioContextClass) return false; this.context = new this.AudioContextClass(); for (const bus of ['music','sfx','ambience']) { const gain = this.context.createGain(); gain.connect(this.context.destination); this.buses.set(bus, gain); } return true; }
  play(cue, { bus = 'sfx', volume = .3 } = {}) { if (!this.context) return null; if (cue.startsWith('music_')) return this.playMusic(cue.slice(6), bus, volume); const oscillator = this.context.createOscillator(); const gain = this.context.createGain(); const sound = { sword: [170, .11, 'sawtooth'], treasure: [660, .34, 'sine'], fire: [95, .18, 'triangle'], water: [130, .28, 'sine'], danger: [110, .22, 'sawtooth'], footstep: [72, .08, 'triangle'], door: [92, .2, 'square'], magic: [520, .4, 'sine'], rain: [840, .09, 'triangle'], bird: [920, .16, 'sine'] }[cue] ?? [220, .12, 'sine']; oscillator.type = sound[2]; oscillator.frequency.value = sound[0]; oscillator.frequency.exponentialRampToValueAtTime?.(Math.max(40, sound[0] * .72), this.context.currentTime + sound[1]); gain.gain.setValueAtTime(volume, this.context.currentTime); gain.gain.exponentialRampToValueAtTime(.001, this.context.currentTime + sound[1]); oscillator.connect(gain); gain.connect(this.buses.get(bus) ?? this.context.destination); oscillator.start(); oscillator.stop(this.context.currentTime + sound[1] + .01); return oscillator; }
  playMusic(state, bus, volume) { const chords = { village: [196, 246.94, 293.66], exploration: [146.83, 220, 293.66], danger: [73.42, 110, 146.83], combat: [82.41, 123.47, 164.81], dungeon: [65.41, 98, 130.81], story: [174.61, 261.63, 329.63] }; const frequencies = chords[state] ?? chords.exploration; const gain = this.context.createGain(); gain.gain.setValueAtTime(Math.max(.002, volume * .13), this.context.currentTime); gain.connect(this.buses.get(bus) ?? this.context.destination); const oscillators = frequencies.map((frequency, index) => { const oscillator = this.context.createOscillator(); oscillator.type = index === 0 ? 'triangle' : 'sine'; oscillator.frequency.value = frequency; oscillator.detune.value = index * 2 - 2; oscillator.connect(gain); oscillator.start(); return oscillator; }); return { oscillators, gain }; }
  stop(handle) { try { if (handle?.oscillators) { handle.gain.gain.exponentialRampToValueAtTime(.001, this.context.currentTime + .12); for (const oscillator of handle.oscillators) oscillator.stop(this.context.currentTime + .13); } else handle?.stop(); } catch {} }
  setBusVolume(bus, value) { const gain = this.buses.get(bus); if (gain) gain.gain.value = Math.max(0, Math.min(1, value)); }
  async dispose() { await this.context?.close?.(); this.context = null; }
}
